# Introduction
In this notebook I will calculate various advanced statistics for individual players such as efficiency(EFF), true shooting percentage(TS%), etc.

## Notebook Objective
The main objective of this notebook is to join the three datasets (details, advanced_data, player_game_data) to create a new dataset advanced_player_data.

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
TEAM_DATA = 'C:/Users/User/OneDrive/Desktop/DSIP/NBAproject/data/processed/010_details.csv'
PLAYER_DATA  = 'C:/Users/User/OneDrive/Desktop/DSIP/NBAproject/data/processed/004_advanced_data.csv'
DATA_TO_MERGE = 'C:/Users/User/OneDrive/Desktop/DSIP/NBAproject/data/processed/004_player_game_data.csv'

ADVANCED_PLAYER_STATS = 'C:/Users/User/OneDrive/Desktop/DSIP/NBAproject/data/processed/410_advanced_player_data.csv'

# Read in data
## Player game data
This data will be merged with team data

In [3]:
adv_df = pd.read_csv(DATA_TO_MERGE, dtype={"START_POSITION": object, "MIN": "string"})
adv_df.dtypes

SEASON                 int64
GAME_ID                int64
TEAM_ID                int64
PLAYER_ID              int64
PLAYER_NAME           object
TEAM_ABBREVIATION     object
START_POSITION        object
MIN                   string
FGM                  float64
FGA                  float64
FG_PCT               float64
FG3M                 float64
FG3A                 float64
FG3_PCT              float64
FTM                  float64
FTA                  float64
FT_PCT               float64
OREB                 float64
DREB                 float64
REB                  float64
AST                  float64
STL                  float64
BLK                  float64
TO                   float64
PF                   float64
PTS                  float64
PLUS_MINUS           float64
dtype: object

## Advanced data
This data will be merged with team data

In [4]:
player_data = pd.read_csv(PLAYER_DATA, parse_dates=['GAME_DATE_EST'], dtype={"START_POSITION": object, "MIN": "string"})
player_data.dtypes

GAME_ID                       int64
TEAM_ID                       int64
TEAM_ABBREVIATION            object
TEAM_CITY                    object
PLAYER_ID                     int64
PLAYER_NAME                  object
START_POSITION               object
COMMENT                     float64
MIN                          string
FGM                         float64
FGA                         float64
FG_PCT                      float64
FG3M                        float64
FG3A                        float64
FG3_PCT                     float64
FTM                         float64
FTA                         float64
FT_PCT                      float64
OREB                        float64
DREB                        float64
REB                         float64
AST                         float64
STL                         float64
BLK                         float64
TO                          float64
PF                          float64
PTS                         float64
PLUS_MINUS                  float64
GAME_DATE_EST        datetime64[ns]
GAME_STATUS_TEXT             object
HOME_TEAM_ID                  int64
VISITOR_TEAM_ID               int64
SEASON                        int64
TEAM_ID_home                  int64
PTS_home                    float64
FG_PCT_home                 float64
FT_PCT_home                 float64
FG3_PCT_home                float64
AST_home                    float64
REB_home                    float64
TEAM_ID_away                  int64
PTS_away                    float64
FG_PCT_away                 float64
FT_PCT_away                 float64
FG3_PCT_away                float64
AST_away                    float64
REB_away                    float64
HOME_TEAM_WINS                int64
dtype: object

In [13]:
team_df = pd.read_csv(TEAM_DATA)
team_df.dtypes

GAME_ID         int64
TEAM_ID         int64
FGM           float64
FGA           float64
FG_PCT        float64
FG3M          float64
FG3A          float64
FG3_PCT       float64
FTM           float64
FTA           float64
FT_PCT        float64
OREB          float64
DREB          float64
REB           float64
AST           float64
STL           float64
BLK           float64
TO            float64
PF            float64
PTS           float64
PLUS_MINUS    float64
SEASON          int64
dtype: object

In [5]:
adv_df

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17:06,0.0,2.0,...,0.0,2.0,2.0,1.0,0.0,1.0,1.0,2.0,0.0,-31.0
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24:58,4.0,17.0,...,1.0,6.0,7.0,2.0,2.0,1.0,5.0,3.0,9.0,-2.0
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22:45,5.0,8.0,...,2.0,2.0,4.0,0.0,0.0,1.0,0.0,2.0,13.0,-23.0
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31:30,8.0,15.0,...,1.0,3.0,4.0,3.0,2.0,0.0,4.0,0.0,25.0,-7.0
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26:48,8.0,14.0,...,1.0,4.0,5.0,6.0,1.0,0.0,0.0,2.0,24.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491732,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
491733,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
491734,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
491735,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
491736,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

In [6]:
def format_minutes(row):
    minute = row['MIN'][0:2]
    if len(minute) > 1:
        if minute[1] == ":":
            return int(minute[0])
        else:
            return int(row['MIN'][0:2])
    else:
        return int(row['MIN'][0])

In [7]:
adv_df['MIN'] = adv_df.apply(lambda row: format_minutes(row), axis=1)
adv_df

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,0.0,2.0,2.0,1.0,0.0,1.0,1.0,2.0,0.0,-31.0
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24,4.0,17.0,...,1.0,6.0,7.0,2.0,2.0,1.0,5.0,3.0,9.0,-2.0
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22,5.0,8.0,...,2.0,2.0,4.0,0.0,0.0,1.0,0.0,2.0,13.0,-23.0
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31,8.0,15.0,...,1.0,3.0,4.0,3.0,2.0,0.0,4.0,0.0,25.0,-7.0
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26,8.0,14.0,...,1.0,4.0,5.0,6.0,1.0,0.0,0.0,2.0,24.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491732,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
491733,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
491734,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
491735,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
491736,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

There are some unacceptable values in the `MIN` column. No game in recent history is longer than 68 minutes and obviously a plyer can't play a negative number of minutes.

In [8]:
adv_df['MIN'].min(), adv_df['MIN'].max()

(-9, 96)

In [9]:
adv_df.shape

(491737, 27)

In [10]:
adv_df[(adv_df['MIN'] > 68) | (adv_df['MIN'] < 1)].shape

(5178, 27)

In [11]:
adv_df = adv_df[(adv_df['MIN'] < 68) & (adv_df['MIN'] > 0)]
adv_df.shape

(486559, 27)

In [12]:
print(491737-5178)

486559

In [14]:
new_df = pd.merge(adv_df, team_df,  how='left', left_on=['GAME_ID','TEAM_ID'], right_on = ['GAME_ID','TEAM_ID'], suffixes=(None, '_TEAM'))
new_df.columns

Index(['SEASON', 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME',
       'TEAM_ABBREVIATION', 'START_POSITION', 'MIN', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS', 'PLUS_MINUS', 'FGM_TEAM',
       'FGA_TEAM', 'FG_PCT_TEAM', 'FG3M_TEAM', 'FG3A_TEAM', 'FG3_PCT_TEAM',
       'FTM_TEAM', 'FTA_TEAM', 'FT_PCT_TEAM', 'OREB_TEAM', 'DREB_TEAM',
       'REB_TEAM', 'AST_TEAM', 'STL_TEAM', 'BLK_TEAM', 'TO_TEAM', 'PF_TEAM',
       'PTS_TEAM', 'PLUS_MINUS_TEAM', 'SEASON_TEAM'],
      dtype='object')

In [15]:
new_df

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,DREB_TEAM,REB_TEAM,AST_TEAM,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,41.0,52.0,21.0,7.0,6.0,20.0,23.0,117.0,-15.0,2020
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24,4.0,17.0,...,41.0,52.0,21.0,7.0,6.0,20.0,23.0,117.0,-15.0,2020
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22,5.0,8.0,...,41.0,52.0,21.0,7.0,6.0,20.0,23.0,117.0,-15.0,2020
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31,8.0,15.0,...,41.0,52.0,21.0,7.0,6.0,20.0,23.0,117.0,-15.0,2020
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26,8.0,14.0,...,41.0,52.0,21.0,7.0,6.0,20.0,23.0,117.0,-15.0,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486554,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,25.0,34.0,25.0,13.0,3.0,26.0,24.0,106.0,0.0,2012
486555,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,25.0,34.0,25.0,13.0,3.0,26.0,24.0,106.0,0.0,2012
486556,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,25.0,34.0,25.0,13.0,3.0,26.0,24.0,106.0,0.0,2012
486557,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,25.0,34.0,25.0,13.0,3.0,26.0,24.0,106.0,0.0,2012
486558,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,25.0,34.0,25.0,13.0,3.0,26.0,24.0,106.0,0.0,2012

In [16]:
new_df.columns

Index(['SEASON', 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME',
       'TEAM_ABBREVIATION', 'START_POSITION', 'MIN', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS', 'PLUS_MINUS', 'FGM_TEAM',
       'FGA_TEAM', 'FG_PCT_TEAM', 'FG3M_TEAM', 'FG3A_TEAM', 'FG3_PCT_TEAM',
       'FTM_TEAM', 'FTA_TEAM', 'FT_PCT_TEAM', 'OREB_TEAM', 'DREB_TEAM',
       'REB_TEAM', 'AST_TEAM', 'STL_TEAM', 'BLK_TEAM', 'TO_TEAM', 'PF_TEAM',
       'PTS_TEAM', 'PLUS_MINUS_TEAM', 'SEASON_TEAM'],
      dtype='object')

In [17]:
new_df['USG%'] = 100*((new_df['FGA']+0.44*new_df['FTA']+new_df['TO']) * 48)/\
                (new_df['MIN']*(new_df['FGA_TEAM']+0.44*new_df['FTA_TEAM']+new_df['TO_TEAM']))

In [18]:
new_df[new_df['PLAYER_NAME'] == 'Luka Doncic']

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,REB_TEAM,AST_TEAM,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%
416,2020,12000036,1610612742,1629029,Luka Doncic,DAL,G,27,6.0,18.0,...,45.0,28.0,1.0,8.0,14.0,25.0,127.0,-11.0,2020,37.218638
752,2020,12000022,1610612742,1629029,Luka Doncic,DAL,G,29,9.0,20.0,...,49.0,22.0,4.0,2.0,9.0,18.0,128.0,80.0,2020,39.285970
1077,2020,12000009,1610612742,1629029,Luka Doncic,DAL,G,16,5.0,13.0,...,51.0,26.0,8.0,2.0,13.0,19.0,109.0,55.0,2020,36.020583
2197,2019,41900156,1610612742,1629029,Luka Doncic,DAL,G,41,15.0,28.0,...,42.0,20.0,5.0,3.0,12.0,15.0,97.0,-70.0,2019,39.052906
2309,2019,41900155,1610612742,1629029,Luka Doncic,DAL,G,31,6.0,17.0,...,31.0,19.0,8.0,6.0,13.0,22.0,111.0,-215.0,2019,38.750960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304399,2018,21800032,1610612742,1629029,Luka Doncic,DAL,F,36,8.0,16.0,...,42.0,29.0,8.0,8.0,16.0,28.0,140.0,20.0,2018,26.840364
304984,2018,21800013,1610612742,1629029,Luka Doncic,DAL,F,31,5.0,16.0,...,38.0,28.0,7.0,5.0,9.0,16.0,100.0,-105.0,2018,30.557961
305216,2018,11800071,1610612742,1629029,Luka Doncic,DAL,F,30,6.0,14.0,...,42.0,21.0,9.0,4.0,21.0,23.0,118.0,-25.0,2018,21.673307
305655,2018,11800047,1610612742,1629029,Luka Doncic,DAL,F,26,4.0,8.0,...,43.0,27.0,13.0,6.0,21.0,26.0,115.0,15.0,2018,21.557261
306250,2018,11800028,1610612742,1629029,Luka Doncic,DAL,F,30,4.0,11.0,...,39.0,27.0,11.0,9.0,15.0,24.0,114.0,-30.0,2018,24.000000

In [19]:
new_df.max()

SEASON                         2020
GAME_ID                    51900111
TEAM_ID                  1610612766
PLAYER_ID                1962936495
PLAYER_NAME          Zylan Cheatham
TEAM_ABBREVIATION               WAS
MIN                              65
FGM                            28.0
FGA                            50.0
FG_PCT                          1.0
FG3M                           14.0
FG3A                           24.0
FG3_PCT                         1.0
FTM                            26.0
FTA                            39.0
FT_PCT                          1.0
OREB                           18.0
DREB                           25.0
REB                            31.0
AST                            25.0
STL                            10.0
BLK                            12.0
TO                             12.0
PF                             15.0
PTS                            81.0
PLUS_MINUS                     57.0
FGM_TEAM                       63.0
FGA_TEAM                      129.0
FG_PCT_TEAM                0.684211
FG3M_TEAM                      27.0
FG3A_TEAM                      70.0
FG3_PCT_TEAM                    1.0
FTM_TEAM                       52.0
FTA_TEAM                       64.0
FT_PCT_TEAM                     1.0
OREB_TEAM                      44.0
DREB_TEAM                      56.0
REB_TEAM                       81.0
AST_TEAM                       47.0
STL_TEAM                       22.0
BLK_TEAM                       20.0
TO_TEAM                        37.0
PF_TEAM                        45.0
PTS_TEAM                      168.0
PLUS_MINUS_TEAM               305.0
SEASON_TEAM                    2020
USG%                     826.861314
dtype: object

Because some of the `MIN` data is incorrect we need to remove all `USG%` over 100

In [20]:
new_df = new_df[new_df['USG%'] < 100]

In [21]:
new_df['TS%'] = new_df['PTS']/( 2*(new_df['FGA']+0.44*new_df['FTA']) )
new_df[new_df['PLAYER_NAME'] == 'Luka Doncic']

<ipython-input-21-539ce648a4ab>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['TS%'] = new_df['PTS']/( 2*(new_df['FGA']+0.44*new_df['FTA']) )

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,AST_TEAM,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%
416,2020,12000036,1610612742,1629029,Luka Doncic,DAL,G,27,6.0,18.0,...,28.0,1.0,8.0,14.0,25.0,127.0,-11.0,2020,37.218638,0.455373
752,2020,12000022,1610612742,1629029,Luka Doncic,DAL,G,29,9.0,20.0,...,22.0,4.0,2.0,9.0,18.0,128.0,80.0,2020,39.285970,0.553279
1077,2020,12000009,1610612742,1629029,Luka Doncic,DAL,G,16,5.0,13.0,...,26.0,8.0,2.0,13.0,19.0,109.0,55.0,2020,36.020583,0.500000
2197,2019,41900156,1610612742,1629029,Luka Doncic,DAL,G,41,15.0,28.0,...,20.0,5.0,3.0,12.0,15.0,97.0,-70.0,2019,39.052906,0.602792
2309,2019,41900155,1610612742,1629029,Luka Doncic,DAL,G,31,6.0,17.0,...,19.0,8.0,6.0,13.0,22.0,111.0,-215.0,2019,38.750960,0.474957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304399,2018,21800032,1610612742,1629029,Luka Doncic,DAL,F,36,8.0,16.0,...,29.0,8.0,8.0,16.0,28.0,140.0,20.0,2018,26.840364,0.651303
304984,2018,21800013,1610612742,1629029,Luka Doncic,DAL,F,31,5.0,16.0,...,28.0,7.0,5.0,9.0,16.0,100.0,-105.0,2018,30.557961,0.296209
305216,2018,11800071,1610612742,1629029,Luka Doncic,DAL,F,30,6.0,14.0,...,21.0,9.0,4.0,21.0,23.0,118.0,-25.0,2018,21.673307,0.587467
305655,2018,11800047,1610612742,1629029,Luka Doncic,DAL,F,26,4.0,8.0,...,27.0,13.0,6.0,21.0,26.0,115.0,15.0,2018,21.557261,0.768443
306250,2018,11800028,1610612742,1629029,Luka Doncic,DAL,F,30,4.0,11.0,...,27.0,11.0,9.0,15.0,24.0,114.0,-30.0,2018,24.000000,0.403226

In [22]:
new_df['EFF'] = new_df['PTS']+new_df['DREB']+new_df['OREB']+\
                            new_df['AST']+new_df['STL']+new_df['BLK']-\
                            (new_df['FGA']-new_df['FGM'])-(new_df['FTA']-new_df['FTM'])-\
                            new_df['TO']
new_df

<ipython-input-22-36a3d894598b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['EFF'] = new_df['PTS']+new_df['DREB']+new_df['OREB']+\

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,7.077697,0.000000,1.0
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24,4.0,17.0,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,38.235294,0.251678,2.0
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22,5.0,8.0,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,16.188624,0.731982,15.0
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31,8.0,15.0,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,26.289460,0.765931,23.0
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26,8.0,14.0,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,23.632250,0.783290,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486554,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,13.0,3.0,26.0,24.0,106.0,0.0,2012,28.874703,0.703642,14.0
486555,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,13.0,3.0,26.0,24.0,106.0,0.0,2012,28.740331,0.705329,14.0
486556,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,13.0,3.0,26.0,24.0,106.0,0.0,2012,19.573576,0.428571,11.0
486557,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,13.0,3.0,26.0,24.0,106.0,0.0,2012,12.980371,0.531915,0.0
486558,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,13.0,3.0,26.0,24.0,106.0,0.0,2012,21.375587,0.515464,7.0

In [23]:
new_df[new_df['PLAYER_NAME'] == 'Luka Doncic'].head()

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF
416,2020,12000036,1610612742,1629029,Luka Doncic,DAL,G,27,6.0,18.0,...,1.0,8.0,14.0,25.0,127.0,-11.0,2020,37.218638,0.455373,15.0
752,2020,12000022,1610612742,1629029,Luka Doncic,DAL,G,29,9.0,20.0,...,4.0,2.0,9.0,18.0,128.0,80.0,2020,39.285970,0.553279,21.0
1077,2020,12000009,1610612742,1629029,Luka Doncic,DAL,G,16,5.0,13.0,...,8.0,2.0,13.0,19.0,109.0,55.0,2020,36.020583,0.500000,10.0
2197,2019,41900156,1610612742,1629029,Luka Doncic,DAL,G,41,15.0,28.0,...,5.0,3.0,12.0,15.0,97.0,-70.0,2019,39.052906,0.602792,35.0
2309,2019,41900155,1610612742,1629029,Luka Doncic,DAL,G,31,6.0,17.0,...,8.0,6.0,13.0,22.0,111.0,-215.0,2019,38.750960,0.474957,14.0

In [24]:
new_df.groupby(['PLAYER_ID', 'PLAYER_NAME']).mean()

,,SEASON,GAME_ID,TEAM_ID,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,...,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF
PLAYER_ID,PLAYER_NAME,,,,,,,,,,,,,,,,,,,,,
15,Eric Piatkowski,2004.371134,2.136553e+07,1.610613e+09,10.592784,1.298969,3.242268,0.336216,0.737113,1.907216,0.289067,...,6.809278,4.747423,15.340206,23.510309,96.912371,9.051546,2004.371134,17.240636,0.534060,3.335052
42,Monty Williams,2003.000000,1.030001e+07,1.610613e+09,5.000000,1.000000,4.000000,0.250000,0.000000,0.000000,0.000000,...,7.000000,3.000000,19.000000,30.000000,79.000000,0.000000,2003.000000,52.004334,0.250000,2.000000
43,Chris Whitney,2003.000000,1.963361e+07,1.610613e+09,11.533333,1.266667,2.933333,0.355733,0.600000,1.200000,0.316667,...,8.666667,5.533333,16.466667,21.666667,86.200000,-45.666667,2003.000000,11.528634,0.593763,3.666667
56,Gary Payton,2004.419786,2.300936e+07,1.610613e+09,29.085561,3.652406,8.286096,0.416024,0.622995,2.136364,0.241289,...,7.419786,5.024064,14.128342,22.724599,97.018717,8.385027,2004.419786,16.460840,0.490487,11.125668
57,Doug Christie,2003.603550,2.124841e+07,1.610613e+09,30.260355,3.165680,7.378698,0.401692,0.461538,1.461538,0.180817,...,8.562130,4.384615,14.023669,21.071006,100.147929,12.437870,2003.603550,15.025482,0.482056,11.633136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122683568,Vernon Macklin,2011.000000,1.110002e+07,1.610613e+09,9.000000,1.000000,2.000000,0.500000,0.000000,0.000000,0.000000,...,8.000000,5.000000,24.000000,25.000000,90.000000,0.000000,2011.000000,14.743826,0.500000,5.000000
1962936250,Wesley Matthews,2009.000000,1.090004e+07,1.610613e+09,24.500000,5.000000,8.500000,0.607000,1.500000,2.500000,0.375000,...,10.000000,5.500000,15.500000,29.000000,100.000000,0.000000,2009.000000,22.051319,0.700713,11.500000
1962936483,Jan Vesely,2011.000000,1.110000e+07,1.610613e+09,22.000000,3.000000,7.000000,0.429000,0.000000,0.000000,0.000000,...,12.000000,4.000000,20.000000,21.000000,78.000000,0.000000,2011.000000,17.473436,0.444162,6.000000
1962936489,Brian Skinner,2011.000000,1.110000e+07,1.610613e+09,28.000000,2.000000,5.000000,0.400000,0.000000,0.000000,0.000000,...,4.000000,9.000000,21.000000,22.000000,90.000000,0.000000,2011.000000,8.383635,0.400000,13.000000
1962936495,Damien Wilkins,2011.000000,1.110002e+07,1.610613e+09,23.000000,1.000000,4.000000,0.250000,0.000000,1.000000,0.000000,...,8.000000,5.000000,24.000000,25.000000,90.000000,0.000000,2011.000000,7.692431,0.250000,5.000000

In [25]:
player_data[['GAME_ID', 'PLAYER_ID', 'GAME_DATE_EST']]

         GAME_ID  PLAYER_ID GAME_DATE_EST
0       12000047    1628998    2020-12-19
1       12000047    1629023    2020-12-19
2       12000047     203469    2020-12-19
3       12000047    1628984    2020-12-19
4       12000047    1626179    2020-12-19
...          ...        ...           ...
491732  11200005     202706    2012-10-06
491733  11200005     202702    2012-10-06
491734  11200005     201585    2012-10-06
491735  11200005     202389    2012-10-06
491736  11200005     201951    2012-10-06

[491737 rows x 3 columns]

In [26]:
full_advanced_data = pd.merge(new_df, player_data[['GAME_ID', 'PLAYER_ID', 'GAME_DATE_EST']],  how='left', left_on=['GAME_ID', 'PLAYER_ID'], right_on = ['GAME_ID', 'PLAYER_ID'])
full_advanced_data

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF,GAME_DATE_EST
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,6.0,20.0,23.0,117.0,-15.0,2020,7.077697,0.000000,1.0,2020-12-19
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24,4.0,17.0,...,6.0,20.0,23.0,117.0,-15.0,2020,38.235294,0.251678,2.0,2020-12-19
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22,5.0,8.0,...,6.0,20.0,23.0,117.0,-15.0,2020,16.188624,0.731982,15.0,2020-12-19
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31,8.0,15.0,...,6.0,20.0,23.0,117.0,-15.0,2020,26.289460,0.765931,23.0,2020-12-19
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26,8.0,14.0,...,6.0,20.0,23.0,117.0,-15.0,2020,23.632250,0.783290,30.0,2020-12-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485898,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,3.0,26.0,24.0,106.0,0.0,2012,28.874703,0.703642,14.0,2012-10-06
485899,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,3.0,26.0,24.0,106.0,0.0,2012,28.740331,0.705329,14.0,2012-10-06
485900,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,3.0,26.0,24.0,106.0,0.0,2012,19.573576,0.428571,11.0,2012-10-06
485901,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,3.0,26.0,24.0,106.0,0.0,2012,12.980371,0.531915,0.0,2012-10-06
485902,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,3.0,26.0,24.0,106.0,0.0,2012,21.375587,0.515464,7.0,2012-10-06

In [27]:
full_advanced_data.dtypes.tail()

SEASON_TEAM               int64
USG%                    float64
TS%                     float64
EFF                     float64
GAME_DATE_EST    datetime64[ns]
dtype: object

In [28]:
full_advanced_data.sort_values(by='GAME_DATE_EST')

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF,GAME_DATE_EST
187704,2003,10300001,1610612742,1505,Tariq Abdul-Wahad,DAL,NaN,5,1.0,5.0,...,4.0,18.0,34.0,85.0,0.0,2003,44.776119,0.200000,6.0,2003-10-05
187680,2003,10300001,1610612762,2144,Ademola Okulaja,UTA,NaN,5,1.0,1.0,...,4.0,18.0,26.0,90.0,0.0,2003,18.648019,1.000000,3.0,2003-10-05
187681,2003,10300001,1610612762,1905,Andrei Kirilenko,UTA,NaN,5,0.0,5.0,...,4.0,18.0,26.0,90.0,0.0,2003,92.121212,0.085034,1.0,2003-10-05
187682,2003,10300001,1610612762,1052,Ben Handlogten,UTA,NaN,5,2.0,4.0,...,4.0,18.0,26.0,90.0,0.0,2003,64.149184,0.409836,4.0,2003-10-05
187683,2003,10300001,1610612762,2306,Carlos Arroyo,UTA,NaN,5,1.0,1.0,...,4.0,18.0,26.0,90.0,0.0,2003,9.324009,1.000000,5.0,2003-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2020,12000049,1610612737,1628381,John Collins,ATL,F,23,5.0,8.0,...,1.0,18.0,28.0,117.0,5.0,2020,19.491255,0.735294,18.0,2020-12-19
56,2020,12000049,1610612737,1629631,De'Andre Hunter,ATL,F,26,0.0,7.0,...,1.0,18.0,28.0,117.0,5.0,2020,15.025402,0.228311,1.0,2020-12-19
55,2020,12000048,1610612764,1630216,Cassius Winston,WAS,NaN,4,0.0,0.0,...,3.0,17.0,14.0,99.0,15.0,2020,19.957537,0.568182,1.0,2020-12-19
68,2020,12000049,1610612737,1630233,Nathan Knight,ATL,NaN,2,1.0,1.0,...,1.0,18.0,28.0,117.0,5.0,2020,20.013342,1.000000,3.0,2020-12-19
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,6.0,20.0,23.0,117.0,-15.0,2020,7.077697,0.000000,1.0,2020-12-19

In [29]:
import matplotlib.pylab as plt
from matplotlib.ticker import ScalarFormatter, StrMethodFormatter

import seaborn as sns

In [30]:
full_advanced_data[full_advanced_data.duplicated(subset=['GAME_DATE_EST','PLAYER_ID'], keep=False)]

Empty DataFrame
Columns: [SEASON, GAME_ID, TEAM_ID, PLAYER_ID, PLAYER_NAME, TEAM_ABBREVIATION, START_POSITION, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TO, PF, PTS, PLUS_MINUS, FGM_TEAM, FGA_TEAM, FG_PCT_TEAM, FG3M_TEAM, FG3A_TEAM, FG3_PCT_TEAM, FTM_TEAM, FTA_TEAM, FT_PCT_TEAM, OREB_TEAM, DREB_TEAM, REB_TEAM, AST_TEAM, STL_TEAM, BLK_TEAM, TO_TEAM, PF_TEAM, PTS_TEAM, PLUS_MINUS_TEAM, SEASON_TEAM, USG%, TS%, EFF, GAME_DATE_EST]
Index: []

[0 rows x 51 columns]

In [31]:
full_advanced_data

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF,GAME_DATE_EST
0,2020,12000047,1610612766,1628998,Cody Martin,CHA,F,17,0.0,2.0,...,6.0,20.0,23.0,117.0,-15.0,2020,7.077697,0.000000,1.0,2020-12-19
1,2020,12000047,1610612766,1629023,P.J. Washington,CHA,F,24,4.0,17.0,...,6.0,20.0,23.0,117.0,-15.0,2020,38.235294,0.251678,2.0,2020-12-19
2,2020,12000047,1610612766,203469,Cody Zeller,CHA,C,22,5.0,8.0,...,6.0,20.0,23.0,117.0,-15.0,2020,16.188624,0.731982,15.0,2020-12-19
3,2020,12000047,1610612766,1628984,Devonte' Graham,CHA,G,31,8.0,15.0,...,6.0,20.0,23.0,117.0,-15.0,2020,26.289460,0.765931,23.0,2020-12-19
4,2020,12000047,1610612766,1626179,Terry Rozier,CHA,G,26,8.0,14.0,...,6.0,20.0,23.0,117.0,-15.0,2020,23.632250,0.783290,30.0,2020-12-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485898,2012,11200005,1610612743,202706,Jordan Hamilton,DEN,NaN,19,4.0,9.0,...,3.0,26.0,24.0,106.0,0.0,2012,28.874703,0.703642,14.0,2012-10-06
485899,2012,11200005,1610612743,202702,Kenneth Faried,DEN,NaN,23,7.0,11.0,...,3.0,26.0,24.0,106.0,0.0,2012,28.740331,0.705329,14.0,2012-10-06
485900,2012,11200005,1610612743,201585,Kosta Koufos,DEN,NaN,15,3.0,7.0,...,3.0,26.0,24.0,106.0,0.0,2012,19.573576,0.428571,11.0,2012-10-06
485901,2012,11200005,1610612743,202389,Timofey Mozgov,DEN,NaN,19,1.0,1.0,...,3.0,26.0,24.0,106.0,0.0,2012,12.980371,0.531915,0.0,2012-10-06
485902,2012,11200005,1610612743,201951,Ty Lawson,DEN,NaN,27,3.0,6.0,...,3.0,26.0,24.0,106.0,0.0,2012,21.375587,0.515464,7.0,2012-10-06

In [32]:
full_advanced_data.set_index(['GAME_DATE_EST', 'PLAYER_NAME']).drop_duplicates()

                               SEASON   GAME_ID     TEAM_ID  PLAYER_ID  \
GAME_DATE_EST PLAYER_NAME
2020-12-19    Cody Martin        2020  12000047  1610612766    1628998
              P.J. Washington    2020  12000047  1610612766    1629023
              Cody Zeller        2020  12000047  1610612766     203469
              Devonte' Graham    2020  12000047  1610612766    1628984
              Terry Rozier       2020  12000047  1610612766    1626179
...                               ...       ...         ...        ...
2012-10-06    Jordan Hamilton    2012  11200005  1610612743     202706
              Kenneth Faried     2012  11200005  1610612743     202702
              Kosta Koufos       2012  11200005  1610612743     201585
              Timofey Mozgov     2012  11200005  1610612743     202389
              Ty Lawson          2012  11200005  1610612743     201951

                              TEAM_ABBREVIATION START_POSITION  MIN  FGM  \
GAME_DATE_EST PLAYER_NAME
2020-12-19    Cody Martin                   CHA              F   17  0.0
              P.J. Washington               CHA              F   24  4.0
              Cody Zeller                   CHA              C   22  5.0
              Devonte' Graham               CHA              G   31  8.0
              Terry Rozier                  CHA              G   26  8.0
...                                         ...            ...  ...  ...
2012-10-06    Jordan Hamilton               DEN            NaN   19  4.0
              Kenneth Faried                DEN            NaN   23  7.0
              Kosta Koufos                  DEN            NaN   15  3.0
              Timofey Mozgov                DEN            NaN   19  1.0
              Ty Lawson                     DEN            NaN   27  3.0

                                FGA  FG_PCT  ...  STL_TEAM  BLK_TEAM  TO_TEAM  \
GAME_DATE_EST PLAYER_NAME                    ...
2020-12-19    Cody Martin       2.0   0.000  ...       7.0       6.0     20.0
              P.J. Washington  17.0   0.235  ...       7.0       6.0     20.0
              Cody Zeller       8.0   0.625  ...       7.0       6.0     20.0
              Devonte' Graham  15.0   0.533  ...       7.0       6.0     20.0
              Terry Rozier     14.0   0.571  ...       7.0       6.0     20.0
...                             ...     ...  ...       ...       ...      ...
2012-10-06    Jordan Hamilton   9.0   0.444  ...      13.0       3.0     26.0
              Kenneth Faried   11.0   0.636  ...      13.0       3.0     26.0
              Kosta Koufos      7.0   0.429  ...      13.0       3.0     26.0
              Timofey Mozgov    1.0   1.000  ...      13.0       3.0     26.0
              Ty Lawson         6.0   0.500  ...      13.0       3.0     26.0

                               PF_TEAM  PTS_TEAM  PLUS_MINUS_TEAM  \
GAME_DATE_EST PLAYER_NAME
2020-12-19    Cody Martin         23.0     117.0            -15.0
              P.J. Washington     23.0     117.0            -15.0
              Cody Zeller         23.0     117.0            -15.0
              Devonte' Graham     23.0     117.0            -15.0
              Terry Rozier        23.0     117.0            -15.0
...                                ...       ...              ...
2012-10-06    Jordan Hamilton     24.0     106.0              0.0
              Kenneth Faried      24.0     106.0              0.0
              Kosta Koufos        24.0     106.0              0.0
              Timofey Mozgov      24.0     106.0              0.0
              Ty Lawson           24.0     106.0              0.0

                               SEASON_TEAM       USG%       TS%   EFF
GAME_DATE_EST PLAYER_NAME
2020-12-19    Cody Martin             2020   7.077697  0.000000   1.0
              P.J. Washington         2020  38.235294  0.251678   2.0
              Cody Zeller             2020  16.188624  0.731982  15.0
              Devonte' Graham         2020  26.289460  0.765931  23.0
              Terry Rozier            2020  23.632250  0.783290  30.0
...                                    ...        ...       ...   ...
2012-10-06    Jordan Hamilton         2012  28.874703  0.703642  14.0
              Kenneth Faried          2012  28.740331  0.705329  14.0
              Kosta Koufos            2012  19.573576  0.428571  11.0
              Timofey Mozgov          2012  12.980371  0.531915   0.0
              Ty Lawson               2012  21.375587  0.515464   7.0

[485903 rows x 49 columns]

In [33]:
full_advanced_data = full_advanced_data.sort_values(by='GAME_DATE_EST')

In [34]:
prec = full_advanced_data.groupby(['GAME_DATE_EST', 'PLAYER_NAME']).sum().drop_duplicates()
prec = prec.reset_index()

In [35]:
prec

,GAME_DATE_EST,PLAYER_NAME,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,MIN,FGM,FGA,FG_PCT,...,STL_TEAM,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF
0,2003-10-05,Ademola Okulaja,2003,10300001,1610612762,2144,5,1.0,1.0,1.000,...,8.0,4.0,18.0,26.0,90.0,0.0,2003,18.648019,1.000000,3.0
1,2003-10-05,Andrei Kirilenko,2003,10300001,1610612762,1905,5,0.0,5.0,0.000,...,8.0,4.0,18.0,26.0,90.0,0.0,2003,92.121212,0.085034,1.0
2,2003-10-05,Ben Handlogten,2003,10300001,1610612762,1052,5,2.0,4.0,0.500,...,8.0,4.0,18.0,26.0,90.0,0.0,2003,64.149184,0.409836,4.0
3,2003-10-05,Carlos Arroyo,2003,10300001,1610612762,2306,5,1.0,1.0,1.000,...,8.0,4.0,18.0,26.0,90.0,0.0,2003,9.324009,1.000000,5.0
4,2003-10-05,Curtis Borchardt,2003,10300001,1610612762,2414,5,2.0,4.0,0.500,...,8.0,4.0,18.0,26.0,90.0,0.0,2003,37.296037,0.500000,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485886,2020-12-19,Trae Young,2020,12000049,1610612737,1629027,21,4.0,12.0,0.333,...,8.0,1.0,18.0,28.0,117.0,5.0,2020,33.622415,0.409836,9.0
485887,2020-12-19,Troy Brown Jr.,2020,12000048,1610612764,1628972,20,3.0,7.0,0.429,...,14.0,3.0,17.0,14.0,99.0,15.0,2020,21.231423,0.642857,9.0
485888,2020-12-19,Tyus Jones,2020,12000049,1610612763,1626145,11,1.0,4.0,0.250,...,11.0,8.0,21.0,31.0,116.0,-5.0,2020,18.849095,0.469925,6.0
485889,2020-12-19,Wayne Ellington,2020,12000048,1610612765,201961,8,1.0,5.0,0.200,...,12.0,2.0,20.0,19.0,96.0,-15.0,2020,36.687631,0.300000,-1.0
485890,2020-12-19,Xavier Sneed,2020,12000047,1610612766,1630270,4,0.0,1.0,0.000,...,7.0,6.0,20.0,23.0,117.0,-15.0,2020,10.026738,0.000000,-1.0

In [36]:
tmp_for_graph = full_advanced_data.groupby(['GAME_DATE_EST', 'PLAYER_NAME']).sum().drop_duplicates()
tmp_for_graph

                                SEASON   GAME_ID     TEAM_ID  PLAYER_ID  MIN  \
GAME_DATE_EST PLAYER_NAME
2003-10-05    Ademola Okulaja     2003  10300001  1610612762       2144    5
              Andrei Kirilenko    2003  10300001  1610612762       1905    5
              Ben Handlogten      2003  10300001  1610612762       1052    5
              Carlos Arroyo       2003  10300001  1610612762       2306    5
              Curtis Borchardt    2003  10300001  1610612762       2414    5
...                                ...       ...         ...        ...  ...
2020-12-19    Trae Young          2020  12000049  1610612737    1629027   21
              Troy Brown Jr.      2020  12000048  1610612764    1628972   20
              Tyus Jones          2020  12000049  1610612763    1626145   11
              Wayne Ellington     2020  12000048  1610612765     201961    8
              Xavier Sneed        2020  12000047  1610612766    1630270    4

                                FGM   FGA  FG_PCT  FG3M  FG3A  ...  STL_TEAM  \
GAME_DATE_EST PLAYER_NAME                                      ...
2003-10-05    Ademola Okulaja   1.0   1.0   1.000   0.0   0.0  ...       8.0
              Andrei Kirilenko  0.0   5.0   0.000   0.0   3.0  ...       8.0
              Ben Handlogten    2.0   4.0   0.500   0.0   0.0  ...       8.0
              Carlos Arroyo     1.0   1.0   1.000   0.0   0.0  ...       8.0
              Curtis Borchardt  2.0   4.0   0.500   0.0   0.0  ...       8.0
...                             ...   ...     ...   ...   ...  ...       ...
2020-12-19    Trae Young        4.0  12.0   0.333   0.0   5.0  ...       8.0
              Troy Brown Jr.    3.0   7.0   0.429   3.0   5.0  ...      14.0
              Tyus Jones        1.0   4.0   0.250   0.0   3.0  ...      11.0
              Wayne Ellington   1.0   5.0   0.200   1.0   5.0  ...      12.0
              Xavier Sneed      0.0   1.0   0.000   0.0   1.0  ...       7.0

                                BLK_TEAM  TO_TEAM  PF_TEAM  PTS_TEAM  \
GAME_DATE_EST PLAYER_NAME
2003-10-05    Ademola Okulaja        4.0     18.0     26.0      90.0
              Andrei Kirilenko       4.0     18.0     26.0      90.0
              Ben Handlogten         4.0     18.0     26.0      90.0
              Carlos Arroyo          4.0     18.0     26.0      90.0
              Curtis Borchardt       4.0     18.0     26.0      90.0
...                                  ...      ...      ...       ...
2020-12-19    Trae Young             1.0     18.0     28.0     117.0
              Troy Brown Jr.         3.0     17.0     14.0      99.0
              Tyus Jones             8.0     21.0     31.0     116.0
              Wayne Ellington        2.0     20.0     19.0      96.0
              Xavier Sneed           6.0     20.0     23.0     117.0

                                PLUS_MINUS_TEAM  SEASON_TEAM       USG%  \
GAME_DATE_EST PLAYER_NAME
2003-10-05    Ademola Okulaja               0.0         2003  18.648019
              Andrei Kirilenko              0.0         2003  92.121212
              Ben Handlogten                0.0         2003  64.149184
              Carlos Arroyo                 0.0         2003   9.324009
              Curtis Borchardt              0.0         2003  37.296037
...                                         ...          ...        ...
2020-12-19    Trae Young                    5.0         2020  33.622415
              Troy Brown Jr.               15.0         2020  21.231423
              Tyus Jones                   -5.0         2020  18.849095
              Wayne Ellington             -15.0         2020  36.687631
              Xavier Sneed                -15.0         2020  10.026738

                                     TS%  EFF
GAME_DATE_EST PLAYER_NAME
2003-10-05    Ademola Okulaja   1.000000  3.0
              Andrei Kirilenko  0.085034  1.0
              Ben Handlogten    0.409836  4.0
              Carlos Arroyo     1.000000  5.0
              Curtis Borchardt  0.500000  4.0
...                                  ...  ...
2020-12-19    Trae Young        0.409836  9.0
              Troy Brown Jr.    0.642857  9.0
              Tyus Jones        0.469925  6.0
              Wayne Ellington   0.300000 -1.0
              Xavier Sneed      0.000000 -1.0

[485891 rows x 47 columns]

In [37]:
prec = prec.groupby('PLAYER_ID').apply(
    lambda g: g.set_index('GAME_DATE_EST')['USG%'].rolling('7d').mean()
)

In [38]:
full_advanced_data.to_csv(ADVANCED_PLAYER_STATS, index=False)
full_advanced_data.columns, ADVANCED_PLAYER_STATS

(Index(['SEASON', 'GAME_ID', 'TEAM_ID', 'PLAYER_ID', 'PLAYER_NAME',
        'TEAM_ABBREVIATION', 'START_POSITION', 'MIN', 'FGM', 'FGA', 'FG_PCT',
        'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
        'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS', 'PLUS_MINUS', 'FGM_TEAM',
        'FGA_TEAM', 'FG_PCT_TEAM', 'FG3M_TEAM', 'FG3A_TEAM', 'FG3_PCT_TEAM',
        'FTM_TEAM', 'FTA_TEAM', 'FT_PCT_TEAM', 'OREB_TEAM', 'DREB_TEAM',
        'REB_TEAM', 'AST_TEAM', 'STL_TEAM', 'BLK_TEAM', 'TO_TEAM', 'PF_TEAM',
        'PTS_TEAM', 'PLUS_MINUS_TEAM', 'SEASON_TEAM', 'USG%', 'TS%', 'EFF',
        'GAME_DATE_EST'],
       dtype='object'),
 'C:/Users/User/OneDrive/Desktop/DSIP/NBAproject/data/processed/040_advanced_player_data.csv')

In [39]:
full_advanced_data[full_advanced_data['SEASON'] == 2018]

,SEASON,GAME_ID,TEAM_ID,PLAYER_ID,PLAYER_NAME,TEAM_ABBREVIATION,START_POSITION,MIN,FGM,FGA,...,BLK_TEAM,TO_TEAM,PF_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,SEASON_TEAM,USG%,TS%,EFF,GAME_DATE_EST
306283,2018,11800002,1610612738,1627824,Guerschon Yabusele,BOS,NaN,16,3.0,5.0,...,7.0,12.0,35.0,97.0,-35.0,2018,16.422661,0.595238,9.0,2018-09-28
306282,2018,11800002,1610612738,1628464,Daniel Theis,BOS,NaN,13,2.0,5.0,...,7.0,12.0,35.0,97.0,-35.0,2018,17.627185,0.400000,6.0,2018-09-28
306281,2018,11800002,1610612738,1628400,Semi Ojeleye,BOS,NaN,23,0.0,8.0,...,7.0,12.0,35.0,97.0,-35.0,2018,14.745523,0.112613,3.0,2018-09-28
306280,2018,11800002,1610612738,203382,Aron Baynes,BOS,NaN,10,3.0,6.0,...,7.0,12.0,35.0,97.0,-35.0,2018,26.734564,0.583333,6.0,2018-09-28
306279,2018,11800002,1610612738,202694,Marcus Morris Sr.,BOS,NaN,17,5.0,11.0,...,7.0,12.0,35.0,97.0,-35.0,2018,26.959224,0.545455,9.0,2018-09-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276877,2018,41800406,1610612744,202326,DeMarcus Cousins,GSW,NaN,18,4.0,9.0,...,6.0,16.0,23.0,110.0,-20.0,2018,29.499389,0.496689,12.0,2019-06-13
276878,2018,41800406,1610612744,1626188,Quinn Cook,GSW,NaN,12,1.0,3.0,...,6.0,16.0,23.0,110.0,-20.0,2018,10.989011,0.333333,1.0,2019-06-13
276879,2018,41800406,1610612744,2733,Shaun Livingston,GSW,NaN,16,3.0,5.0,...,6.0,16.0,23.0,110.0,-20.0,2018,16.483516,0.600000,4.0,2019-06-13
276871,2018,41800406,1610612744,203110,Draymond Green,GSW,F,44,5.0,10.0,...,6.0,16.0,23.0,110.0,-20.0,2018,18.861139,0.505515,33.0,2019-06-13
276880,2018,41800406,1610612744,201973,Jonas Jerebko,GSW,NaN,2,0.0,0.0,...,6.0,16.0,23.0,110.0,-20.0,2018,0.000000,NaN,0.0,2019-06-13